[build]
command = "npm run build"
publish = "/public"
functions = "src/netlify/functions"


[dev]
port = 8888
functionsPort = 8888
framework = "#static"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/badge/*"
to = "/.netlify/functions/badge"
status = 200
